/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-12 12:12:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage_005fartist;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_005forder_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/mypage_artist/../common/menubar.jsp", Long.valueOf(1589255202411L));
    _jspx_dependants.put("/views/mypage_artist/../common/mypagehead.jsp", Long.valueOf(1589256758489L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang='ko'>\r\n");
      out.write("    <head> \r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>주문 상세 보기</title>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\t\t  <link rel=\"stylesheet\" href=\"../css/bootstrap.css\">\r\n");
      out.write("\t\t<script src=\"../js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/bootstrap.js\"></script> \r\n");
      out.write("        <style>\r\n");
      out.write("            #mypage_text{\r\n");
      out.write("                font-size: 2em;\r\n");
      out.write("                margin-left: 100px;\r\n");
      out.write("                font-family:Verdana, Geneva, Tahoma, sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("            #artist{\r\n");
      out.write("                margin-left: auto;\r\n");
      out.write("            }\r\n");
      out.write("            td{\r\n");
      out.write("                padding: 5px;\r\n");
      out.write("            }\r\n");
      out.write("            #info_change, #card_check{\r\n");
      out.write("                width: 150px;\r\n");
      out.write("            }  \r\n");
      out.write("            b{\r\n");
      out.write("                font-family:Verdana, Geneva, Tahoma, sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("            #mypage_nav > ul > li > a{\r\n");
      out.write("                padding-left: 80px;\r\n");
      out.write("                padding-right: 80px;\r\n");
      out.write("                padding-top: 10px;\r\n");
      out.write("                padding-bottom: 10px;\r\n");
      out.write("                font-size: 1.2em;\r\n");
      out.write("                color: white;\r\n");
      out.write("                transition: all 0.5s;\r\n");
      out.write("            }\r\n");
      out.write("            #mypage_nav > ul > li > a:hover{\r\n");
      out.write("                color: rgb(182, 5, 5);\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("            }\r\n");
      out.write("           \r\n");
      out.write("            select:hover{\r\n");
      out.write("                border-color: royalblue;\r\n");
      out.write("            }\r\n");
      out.write("            select{\r\n");
      out.write("                transition: 0.5s;\r\n");
      out.write("            }\r\n");
      out.write("            td{\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            .info{\r\n");
      out.write("                margin-left: 200px;\r\n");
      out.write("            }\r\n");
      out.write("            #t{\r\n");
      out.write("                border: 1px solid black;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header id=\"menu\">\r\n");
      out.write("       <div id=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/logo-02.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("                 <ul class = \"navi\">\r\n");
      out.write("                    <li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/product/product.jsp\">STORE</a></li>\r\n");
      out.write("                    <li><a href=\"#\">COMMUNITY</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/board/amateur/amateurBoard.jsp\">아마추어 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">NOTICE</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/list.no\">공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/inquiry/inquiryBoard.jsp\">1:1문의</a></li>\r\n");
      out.write("                        </ul>    \r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("        <!--icon :: 색상변경 또는 없애버리고 메뉴바 만들기-->\r\n");
      out.write("        <div id=\"loginWrap\">\r\n");
      out.write("            <a href =\"#\" class=\"icon\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/login2.png\"></a>\r\n");
      out.write("            <a href =\"#\" class=\"icon\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/search2.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header> \r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>MyPage Head</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/Style-mypagehead.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"headline\">\n");
      out.write("        <div class=\"headline-text\">\n");
      out.write("            <hr>\n");
      out.write("            <h3 style=\"font-size: 20px;\"> 작가 마이페이지</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"headline-subbox\">\n");
      out.write("            <div class=\"artist-img\">\n");
      out.write("                <!--Artist Image-->\n");
      out.write("                <img src=\"../img/artist.JPG\" alt=\"artist-img\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"artist-button\">\n");
      out.write("                <button style=\"margin-bottom: 3px;\">정보수정</button>\n");
      out.write("                <button>감동카드 확인</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"second-menu\">\n");
      out.write("        <ul>\n");
      out.write("            <li><a href=\"#\">상품 관리</a></li><a>|</a>\n");
      out.write("            <li><a href=\"#\">주문 관리</a></li><a>|</a>\n");
      out.write("            <li><a href=\"#\">배송 관리</a></li><a>|</a>\n");
      out.write("            <li><a href=\"#\">반품 / 환불 관리</a></li><a>|</a>\n");
      out.write("            <li><a href=\"#\">문의 내역</a></li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <br><br>\r\n");
      out.write("        <h3 align=\"center\">주문 상세 보기</h3>\r\n");
      out.write("        <br>\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("        <form>\r\n");
      out.write("            <h3 class=\"info\"><b>주문 상품</b></h3>\r\n");
      out.write("            <div class=\"container\" >\r\n");
      out.write("                <table class=\"table table-dark table-striped  table-hover\" >\r\n");
      out.write("                <tr >\r\n");
      out.write("                    <td>주문번호</td>\r\n");
      out.write("                    <td>이미지</td>\r\n");
      out.write("                    <td>상품정보</td>\r\n");
      out.write("                    <td>금액</td>\r\n");
      out.write("                    <td>처리상태</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>a0001</td>\r\n");
      out.write("                    <td><img src=\"C:\\Users\\diot0\\Pictures\\Saved Pictures/2.jpg\" width=\"70px\" height=\"70px\"></td>\r\n");
      out.write("                    <td>작품명 : Remember Me <br> 작가명 : 경섭</td>\r\n");
      out.write("                    <td>10,000원</td>\r\n");
      out.write("                    <td>배송중</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br><br>\r\n");
      out.write("            <h3 class=\"info\"><b>결제 정보</b></h3>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <table class=\"table table-dark table-striped table-hover\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>입금자</td>\r\n");
      out.write("                        <td>결제 방법</td>\r\n");
      out.write("                        <td>연락처</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>경섭</td>\r\n");
      out.write("                        <td>무통장 입금</td>\r\n");
      out.write("                        <td>010-1010-1010</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br><br>\r\n");
      out.write("            <h3 class=\"info\"><b>배송 정보</b></h3>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <table class=\"table table-dark table-striped table-hover\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>수령인</td>\r\n");
      out.write("                        <td>배송지</td>\r\n");
      out.write("                        <td>배송 메시지</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>경섭</td>\r\n");
      out.write("                        <td>서울시 중랑구</td>\r\n");
      out.write("                        <td>집 앞에 놔주세요!</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    <br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\t<br><br><br><br><br><br><br><br><br>\r\n");
      out.write("    <br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\t<br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
