CREATE SEQUENCE SEQ_PID START WITH 0; --PAINT 컬럼에사용
CREATE SEQUENCE SEQ_PNO START WITH 0; -- PAINT_PHOTO 컬럼에사용


  CREATE OR REPLACE FORCE VIEW "SEMI"."V_GALLERY" ("작품번호", "작품이름", "작품가격", "카테고리", "작가이름", "작품소개", "작품제작년도", "사이즈번호", "좋아요", "작가아이디") AS 
  SELECT P.PAINT_NO 작품번호 ,PAINT_NAME 작품이름,PAINT_PRICE 작품가격,CATEGORY 카테고리,ARTIST_NAME 작가이름,PAINT_INT 작품소개
            ,PAINT_MDATE 작품제작년도, SIZE_NO 사이즈번호, LIKES 좋아요, M.USER_ID 작가아이디
    FROM PAINT P
    JOIN MASTERPIECE M ON (P.PAINT_NO = M.PAINT_NO)
    JOIN MEMBER ME ON (M.USER_ID = ME.USER_ID);
    
SELECT * FROM PAINT_PHOTO WHERE FILELEVEL=0 AND PAINT_NO BETWEEN 1 AND 10;
