<<<<<<< HEAD
/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
<<<<<<< HEAD
 * Generated at: 2020-05-13 12:01:18 UTC
=======
 * Generated at: 2020-05-11 04:52:44 UTC
>>>>>>> refs/remotes/origin/master
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class noticeBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
<<<<<<< HEAD
    _jspx_dependants.put("/views/board/notice/../../common/menubar.jsp", Long.valueOf(1589370888257L));
    _jspx_dependants.put("/views/board/notice/../../common/footer.jsp", Long.valueOf(1589353251774L));
=======
    _jspx_dependants.put("/views/board/notice/../../common/menubar.jsp", Long.valueOf(1589171124131L));
    _jspx_dependants.put("/views/board/notice/../../common/footer.jsp", Long.valueOf(1589016906147L));
>>>>>>> refs/remotes/origin/master
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

<<<<<<< HEAD
      out.write('\r');
      out.write('\n');

	ArrayList<Notice> list = ((ArrayList<Notice>)request.getAttribute("list"));
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	
	int listCount = pi.getListCount();
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	
	 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>NOTICE</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/bootstrap.css\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/views/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write("\t#noticeCorner{\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t} \r\n");
      out.write("\t#subnav{\r\n");
      out.write("\t\tmargin-left:50px;\r\n");
      out.write("\t\tmargin-top:100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#noticeTable{\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\tmargin-top: 100px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Navigation에서 Notice>공지사항 눌렀을 때 나오는 페이지 (계연) -->\r\n");
      out.write('\r');
      out.write('\n');

	Member loginUser = (Member) session.getAttribute("loginUser");

      out.write("\r\n");
=======
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write(" <link rel=\"stylesheet\" href=\"../../css/style.css\">\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\n");
      out.write(" <link rel=\"stylesheet\" href=\"../../css/bootstrap.css\">\n");
      out.write("<script src=\"../../js/jquery-3.4.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/bootstrap.js\"></script>    \n");
      out.write("\n");
      out.write(" <style>\n");
      out.write(" \t#insertNotice{ float:right; margin-right:100px; }\n");
      out.write(" \t#noticeList div{ margin:0 auto; }\n");
      out.write(" \t#noticeCorner {margin-top:40px;} \n");
      out.write(" </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- Navigation에서 Notice>공지사항 눌렀을 때 나오는 페이지 (계연) -->\n");
>>>>>>> refs/remotes/origin/master
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
<<<<<<< HEAD
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 로그인 팝업 css */\r\n");
      out.write("#LoginBtn input, #memberJoinBtn, #logoutBtn, #myPage {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground: red;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#memberJoinBtn {\r\n");
      out.write("\tbackground: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginBtn:hover\r\n");
      out.write("      #memberJoinBtn:hover, #logoutBtn:hover, #memberJoinBtn:hover,\r\n");
      out.write("\t#myPage:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Login_pop {\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tmargin-top: 70px;\r\n");
      out.write("\t-webkit-transition: all 0.5s;\r\n");
      out.write("\t/* text-align:center; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logout, #myPage {\r\n");
      out.write("\tbackground: orangered;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myPage {\r\n");
      out.write("\tbackground: yellowgreen;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#LoginArea {\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\t/* display:inline-block; */\r\n");
      out.write("\tmargin-left: 35%;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-algin: \"center\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginArea>form, #userInfo {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#LoginArea a img {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 1em;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("\tpadding-right: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding-top: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputinfo {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
=======
>>>>>>> refs/remotes/origin/master
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header id=\"menu\">\r\n");
      out.write("       <div id=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/logo-02.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("                 <ul class = \"navi\">\r\n");
      out.write("                    <li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/product/product.jsp\">STORE</a></li>\r\n");
      out.write("                    <li><a href=\"#\">COMMUNITY</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">아마추어 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">NOTICE</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/board/notice/noticeBoard.jsp\">공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("                        </ul>    \r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("        <!--icon :: 색상변경 또는 없애버리고 메뉴바 만들기-->\r\n");
      out.write("        <div id=\"loginWrap\">\r\n");
      out.write("            <a href =\"#\" class=\"icon\" ><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/login2.png\"></a>\r\n");
      out.write("            <a href =\"#\" class=\"icon\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/search2.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header> \r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\n');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header id=\"menu\">\r\n");
      out.write("       <div id=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/logo-02.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("                 <ul class = \"navi\">\r\n");
      out.write("                    <li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/product/product.jsp\">STORE</a></li>\r\n");
      out.write("                    <li><a href=\"#\">COMMUNITY</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">아마추어 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">NOTICE</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
<<<<<<< HEAD
      out.write("/login.me\"\r\n");
      out.write("\t\t\t\tonsubmit=\"return validate();\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/views/img/close2.png\"></a> <br>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<h1 align=\"center\">로그인</h1>\r\n");
      out.write("\t\t\t\t<table class=\"inputinfo\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>ID:</label>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"userId\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>PW: </label>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"userPwd\" id=\"userPwd\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<div id=\"memberJoinBtn\">회원가입</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"LoginBtn\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\t/* 로그인 팝업창 띄우기  */\r\n");
      out.write("\t\t\t\tfunction login_btn() {\r\n");
      out.write("\t\t\t\t\tif ($(\"#Login_pop\").css('opacity') == '0') {\r\n");
      out.write("\t\t\t\t\t\t$(\"#Login_pop\").css(\"opacity\", \"0.9\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t} else if ($(\"#Login_pop\").css('opacity') == '0.9') {\r\n");
      out.write("\t\t\t\t\t\t$(\"#Login_pop\").css(\"opacity\", \"0\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<div id=\"LoginArea\" >\r\n");
      out.write("\t\t\t\t<label>");
      out.print(loginUser.getUserName());
      out.write("님의 방문을 환영합니다.</label>\r\n");
      out.write("\t\t\t\t<div class=\"btns\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t<div id=\"myPage\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='myPage.me?userId=");
      out.print(loginUser.getUserId());
      out.write("';\">정보수정</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"logoutBtn\" onclick=\"logout();\">로그아웃</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<br clear=\"both\">\r\n");
      out.write("\t<!-- 스크립트 부분 -->\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t/*로그인 입력 안했을 시 => alter창 또는 팝업창 띄운 후, error 페이지로 연결*/\r\n");
      out.write("\t\tfunction validate() {\r\n");
      out.write("\t\t\tif ($(\"#userId\").val().trim().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//비밀번호를 입력하지 않았을 때\r\n");
      out.write("\t\t\tif ($(\"#userPwd\").val().trim().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
=======
      out.write("/views/board/notice/noticeBoard.jsp\">공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("                        </ul>    \r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("        <!--icon :: 색상변경 또는 없애버리고 메뉴바 만들기-->\r\n");
      out.write("        <div id=\"loginWrap\">\r\n");
      out.write("            <a href =\"#\" class=\"icon\" ><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/login2.png\"></a>\r\n");
      out.write("            <a href =\"#\" class=\"icon\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/search2.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header> \r\n");
      out.write("    <br clear=\"both\">\r\n");
>>>>>>> refs/remotes/origin/master
      out.write("</body>\r\n");
      out.write("</html>");
<<<<<<< HEAD
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"noticeCorner\" class=\"containter\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<ul id=\"subnav\" class=\"nav flex-column\">\r\n");
      out.write("\t\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t\t    <a class=\"nav-link active\" href=\"noticeBoard.jsp\">공지사항</a>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t\t    <a class=\"nav-link\" href=\"../inquiry/inquiryBoard.jsp\">1:1문의</a>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\t <div id=\"noticeTable\" class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-hover\" id=\"listArea\">\r\n");
      out.write("\t\t\t\t  \t\t<thead>\r\n");
      out.write("\t\t\t\t    \t\t<tr>\r\n");
      out.write("\t\t\t\t      \t\t\t<th>게시글 번호</th>\r\n");
      out.write("\t\t\t\t      \t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t      \t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t      \t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t    \t\t</tr>\r\n");
      out.write("\t\t\t\t  \t\t</thead>\r\n");
      out.write("\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t  \t\t<tbody>\r\n");
      out.write("\t\t\t\t  \t\t");
if(!list.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t  \t\t\t");
for(Notice n:list){ 
      out.write("\r\n");
      out.write("\t\t\t\t    \t\t<tr>\r\n");
      out.write("\t\t\t\t    \t\t\t<input type=\"hidden\" value=\"");
      out.print(n.getNoti_no() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(n.getNoti_no() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t      \t\t\t<td>");
      out.print(n.getNoti_title() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t      \t\t\t<td>관리자</td>\r\n");
      out.write("\t\t\t\t      \t\t\t<td>");
      out.print(n.getNoti_date() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t</tr>\r\n");
      out.write("\t\t\t\t    \t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t    \t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t    \t\t<tr>\r\n");
      out.write("\t\t\t\t    \t\t\t<td>등록된 게시글이 없습니다.</td>\r\n");
      out.write("\t\t\t\t    \t\t</tr>\r\n");
      out.write("\t\t\t\t    \t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t  \t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Pagination -->\r\n");
      out.write("\t \t<div style=\"text-align:center;\">\r\n");
      out.write("\t\t\t<div class=\"col-mid-12\">\r\n");
      out.write("\t\t\t\t <ul class=\"pagination justify-content-center\" style=\"margin:20px 0\">\r\n");
      out.write("\t    \t    \t     <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.no?currentPage=1\">Previous</a></li>\r\n");
      out.write("\t  \t\t\t\t\t");
for(int p = startPage; p<=endPage; p++){ 
      out.write("\r\n");
      out.write("\t  \t\t\t\t\t \t<li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/list.no?currentPage=");
      out.print(p );
      out.write('"');
      out.write('>');
      out.print(p );
      out.write("</a></li>\r\n");
      out.write("\t  \t\t\t\t\t ");
} 
      out.write("\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t                     <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/list.bo?currentPage=");
      out.print(maxPage);
      out.write("\">Next</a></li>\r\n");
      out.write("\t        \t  </ul>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button id=\"insertNotice\" type=\"button active\" class=\"btn btn-secondary\" onclick=\"location.href='");
=======
      out.write("\n");
      out.write("\t<br clear=\"both\">\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<div id=\"noticeCorner\" class=\"containter\">\n");
      out.write("\t\t\t<div class=\"page-header\">\n");
      out.write("\t   \t\t\t<h1> 공지사항 </h1>\n");
      out.write("\t   \t\t\t<h3> 공지사항 게시판입니다.</h2>\n");
      out.write("\t   \t\t</div>\n");
      out.write("\t<div id=\"noticeList\" class=\"row\">\n");
      out.write("\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<table class=\"table table-hover\">\n");
      out.write("\t\t  \t\t<thead>\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t      \t\t\t<th>게시글 번호</th>\n");
      out.write("\t\t      \t\t\t<th>내용</th>\n");
      out.write("\t\t      \t\t\t<th>작성자</th>\n");
      out.write("\t\t      \t\t\t<th>작성일</th>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t  \t\t</thead>\n");
      out.write("\t\t  \t\t<tbody>\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t      \t\t\t<td>1</td>\n");
      out.write("\t\t      \t\t\t<td>사이트 이용 문의 안내입니다.</td>\n");
      out.write("\t\t      \t\t\t<td>관리자</td>\n");
      out.write("\t\t      \t\t\t<td>2020-03-24</td>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t      \t\t\t<td>2</td>\n");
      out.write("\t\t      \t\t\t<td>4월의 작품 선정 결과(메인페이지 참고)</td>\n");
      out.write("\t\t      \t\t\t<td>관리자</td>\n");
      out.write("\t\t      \t\t\t<td>2020-05-01</td>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t      \t\t\t<td>3</td>\n");
      out.write("\t\t      \t\t\t<td>3월의 작품 선정 결과(메인페이지 참고)</td>\n");
      out.write("\t\t      \t\t\t<td>관리자</td>\n");
      out.write("\t\t      \t\t\t<td>2020-04-01</td>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t    \t\t\t<td>4</td>\n");
      out.write("\t\t      \t\t\t<td>2월의 작품 선정 결과(메인페이지 참고)</td>\n");
      out.write("\t\t      \t\t\t<td>관리자</td>\n");
      out.write("\t\t      \t\t\t<td>2020-03-01</td>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t  \t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("\t\t<div style=\"text-align:center;\">\n");
      out.write("\t\t\t<div class=\"col-mid-12\">\n");
      out.write("\t\t\t\t <ul class=\"pagination justify-content-center\" style=\"margin:20px 0\">\n");
      out.write("\t    \t    \t     <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Previous</a></li>\n");
      out.write("\t  \t\t\t\t\t <li class=\"page-item active\"><a class=\"page-link\" href=\"#\">1</a></li>\n");
      out.write("\t  \t\t\t\t\t <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\n");
      out.write("\t  \t\t\t\t\t <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\n");
      out.write("\t                     <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Next</a></li>\n");
      out.write("\t        \t  </ul>\n");
      out.write("\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t<button id=\"insertNotice\" type=\"button active\" class=\"btn btn-secondary\" \n");
      out.write("\t\tonclick=\"location.href='");
>>>>>>> refs/remotes/origin/master
      out.print(request.getContextPath());
<<<<<<< HEAD
      out.write("/views/board/notice/noticeInsert.jsp'\">게시글 작성</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#listArea td\").click(function(){\r\n");
      out.write("\t\t\tvar noti_no = $(this).parent().children(\"input\").val();\r\n");
      out.write("\t\t\tlocation.href='");
      out.print(request.getContextPath());
      out.write("/detail.no?noti_no='+noti_no;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("<br><br><br>\r\n");
=======
      out.write("/views/board/notice/noticeInsert.jsp'\">게시글 작성</button>\n");
      out.write("</div>\n");
      out.write("<br><br><br>\n");
>>>>>>> refs/remotes/origin/master
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    \"Copyright © 1998-2019 KH Information Educational Institute All Right Reserved\"\r\n");
      out.write("   </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
<<<<<<< HEAD
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/bootstrap.js\"></script>    \r\n");
      out.write("</body>\r\n");
=======
      out.write("\n");
      out.write("</body>\n");
>>>>>>> refs/remotes/origin/master
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
=======
/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-11 04:43:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.notice.model.vo.*;
import java.util.ArrayList;

public final class noticeBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/board/notice/../../common/menubar.jsp", Long.valueOf(1589165393493L));
    _jspx_dependants.put("/views/board/notice/../../common/footer.jsp", Long.valueOf(1589104100954L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("board.notice.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Notice> list = ((ArrayList<Notice>)request.getAttribute("list"));
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	
	int listCount = pi.getListCount();
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	
	 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"../../css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"../../css/bootstrap.css\">\r\n");
      out.write("<script src=\"../../js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/bootstrap.js\"></script>    \r\n");
      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write(" \t#insertNotice{ float:right; margin-right:100px; }\r\n");
      out.write(" \t#noticeList div{margin: 0 auto;}\r\n");
      out.write(" \t#noticeCorner {margin-top:40px;} \r\n");
      out.write("\t#subnav{ float: left; margin-left:20px;}\r\n");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Navigation에서 Notice>공지사항 눌렀을 때 나오는 페이지 (계연) -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"views/css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header id=\"menu\">\r\n");
      out.write("       <div id=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/logo-02.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("                 <ul class = \"navi\">\r\n");
      out.write("                    <li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/product/product.jsp\">STORE</a></li>\r\n");
      out.write("                    <li><a href=\"#\">COMMUNITY</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/board/amateur/amateurBoard.jsp\">아마추어 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">NOTICE</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/list.no\">공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/inquiry/inquiryBoard.jsp\">1:1문의</a></li>\r\n");
      out.write("                        </ul>    \r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("        <!--icon :: 색상변경 또는 없애버리고 메뉴바 만들기-->\r\n");
      out.write("        <div id=\"loginWrap\">\r\n");
      out.write("            <a href =\"#\" class=\"icon\" ><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/login2.png\"></a>\r\n");
      out.write("            <a href =\"#\" class=\"icon\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/search2.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header> \r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"views/css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header id=\"menu\">\r\n");
      out.write("       <div id=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/logo-02.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("                 <ul class = \"navi\">\r\n");
      out.write("                    <li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/product/product.jsp\">STORE</a></li>\r\n");
      out.write("                    <li><a href=\"#\">COMMUNITY</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/board/amateur/amateurBoard.jsp\">아마추어 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">NOTICE</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/list.no\">공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/inquiry/inquiryBoard.jsp\">1:1문의</a></li>\r\n");
      out.write("                        </ul>    \r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("        <!--icon :: 색상변경 또는 없애버리고 메뉴바 만들기-->\r\n");
      out.write("        <div id=\"loginWrap\">\r\n");
      out.write("            <a href =\"#\" class=\"icon\" ><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/login2.png\"></a>\r\n");
      out.write("            <a href =\"#\" class=\"icon\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/search2.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header> \r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<br clear=\"both\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"noticeCorner\" class=\"containter\">\r\n");
      out.write("\t<div id=\"noticeList\" class=\"row\">\r\n");
      out.write("\t\t<ul id=\"subnav\" class=\"nav flex-column\">\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link active\" href=\"noticeBoard.jsp\">공지사항</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" href=\"../inquiry/inquiryBoard.jsp\">1:1문의</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t게시판 리스트 출력 페이지 입니다.\r\n");
      out.write("\t\t\t <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t  \t\t<thead>\r\n");
      out.write("\t\t\t    \t\t<tr>\r\n");
      out.write("\t\t\t      \t\t\t<th>게시글 번호</th>\r\n");
      out.write("\t\t\t      \t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t      \t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t      \t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t    \t\t</tr>\r\n");
      out.write("\t\t\t  \t\t</thead>\r\n");
      out.write("\t\t\t  \t\t<tbody>\r\n");
      out.write("\t\t\t  \t\t");
if(!list.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t");
for(Notice n:list){ 
      out.write("\r\n");
      out.write("\t\t\t    \t\t<tr>\r\n");
      out.write("\t\t\t    \t\t\t<input type=\"hidden\" value=\"");
      out.print(n.getNoti_no() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(n.getNoti_no() );
      out.write("</td>\r\n");
      out.write("\t\t\t      \t\t\t<td>");
      out.print(n.getNoti_title() );
      out.write("</td>\r\n");
      out.write("\t\t\t      \t\t\t<td>관리자</td>\r\n");
      out.write("\t\t\t      \t\t\t<td>");
      out.print(n.getNoti_date() );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t</tr>\r\n");
      out.write("\t\t\t    \t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t    \t");
} else{
      out.write("\r\n");
      out.write("\t\t\t    \t\t\r\n");
      out.write("\t\t\t    \t");
} 
      out.write("\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t  \t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Pagination -->\r\n");
      out.write("\t \t<div style=\"text-align:center;\">\r\n");
      out.write("\t\t\t<div class=\"col-mid-12\">\r\n");
      out.write("\t\t\t\t <ul class=\"pagination justify-content-center\" style=\"margin:20px 0\">\r\n");
      out.write("\t    \t    \t     <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.no?currentPage=1\">Previous</a></li>\r\n");
      out.write("\t  \t\t\t\t\t");
for(int p = startPage; p<=endPage; p++){ 
      out.write("\r\n");
      out.write("\t  \t\t\t\t\t <li class=\"page-item active\"><a class=\"page-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/list.bo?currentPage=");
      out.print(currentPage-1 );
      out.write("'\">1</a></li>\r\n");
      out.write("\t  \t\t\t\t\t <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/list.bo?currentPage=");
      out.print(p );
      out.write('"');
      out.write('>');
      out.print(p );
      out.write("</a></li>\r\n");
      out.write("\t  \t\t\t\t\t ");
} 
      out.write("\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t                     <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/list.bo?currentPage=");
      out.print(maxPage);
      out.write("\">Next</a></li>\r\n");
      out.write("\t        \t  </ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<button id=\"insertNotice\" type=\"button active\" class=\"btn btn-secondary\" \r\n");
      out.write("\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/views/board/notice/noticeInsert.jsp'\">게시글 작성</button>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    \"Copyright © 1998-2019 KH Information Educational Institute All Right Reserved\"\r\n");
      out.write("   </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
>>>>>>> refs/remotes/origin/master
