/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-12 08:37:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menubar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"views/css/style.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("    if($(\"#userId\").val().trim().length==0){\r\n");
      out.write("        alert(\"아이디를 입력하세요\");\r\n");
      out.write("        $(\"#userId\").focus();\r\n");
      out.write("        return false;\r\n");
      out.write("     }\r\n");
      out.write("     //비밀번호를 입력하지 않았을 때\r\n");
      out.write("     if($(\"#userPwd\").val().trim().length==0){\r\n");
      out.write("        alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("        $(\"#userPwd\").focus();\r\n");
      out.write("\r\n");
      out.write("        return false;\r\n");
      out.write("     }\r\n");
      out.write("     return true;\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("   #LoginBtn input, #memberJoinBtn{\r\n");
      out.write("         display:inline-block;\r\n");
      out.write("         vertical-align:middle;\r\n");
      out.write("         text-align:center;\r\n");
      out.write("         background:red;\r\n");
      out.write("         color:white;\r\n");
      out.write("         height:30px;\r\n");
      out.write("         width:100px;\r\n");
      out.write("         float:left;\r\n");
      out.write("      }\r\n");
      out.write("     \r\n");
      out.write("      #memberJoinBtn{\r\n");
      out.write("         background:gray;\r\n");
      out.write("        \r\n");
      out.write("      }\r\n");
      out.write("      #loginBtn:hover\r\n");
      out.write("      #memberJoinBtn:hover{\r\n");
      out.write("         cursor:pointer;\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("#Login_pop {\r\n");
      out.write("\topacity: 0; \r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\theight:100px;\r\n");
      out.write("    width:100%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tmargin-top: 70px;\r\n");
      out.write("\t-webkit-transition: all 0.5s;\r\n");
      out.write("     \t/* text-align:center; */\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#LoginArea {\r\n");
      out.write("\tbackground:black;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\t height:500px;\r\n");
      out.write("     width:450px;\r\n");
      out.write("     \t/* display:inline-block; */\r\n");
      out.write("     margin-left:35%;\r\n");
      out.write("     border-radius:10px;\r\n");
      out.write("      align:\"center\";\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id=\"menu\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\" class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/views/img/logo-02.png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"navi\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/views/product/product.jsp\">STORE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">COMMUNITY</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">아마추어 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">NOTICE</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/views/board/notice/noticeBoard.jsp\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div id=\"loginWrap\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"icon\" onclick=\"login_btn();\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/views/img/login2.png\"></a> <a\r\n");
      out.write("\t\t\t\t\thref=\"#\" class=\"icon\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/views/img/search2.png\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction login_btn() {\r\n");
      out.write("\t\t\t\tif ($(\"#Login_pop\").css('opacity') == '0') {\r\n");
      out.write("\t\t\t\t\t$(\"#Login_pop\").css(\"opacity\", \"0.9\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t} else if ($(\"#Login_pop\").css('opacity') == '0.9') {\r\n");
      out.write("\t\t\t\t\t$(\"#Login_pop\").css(\"opacity\", \"0\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<br clear=\"both\">\r\n");
      out.write("\t<div id=\"Login_pop\">\r\n");
      out.write("\t\t<div id=\"LoginArea\">\r\n");
      out.write("\t\t\t<a href = \"#\" style=\"color:white; font-size:30px; float:right; padding-top:40px; padding-right:50px\">X</a>\r\n");
      out.write("\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t<h1 align=\"center\">로그인</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t  <form method=\"get\" action=\"#\" onsubmit=\"return validate();\">\r\n");
      out.write("      <!-- form 태그의 onsubmit 속성 return validate가 true인지 false인지 에 따라 submit을 할지말지 결정하는 요소 -->\r\n");
      out.write("         <table align=\"center\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td><label>ID:</label><td>\r\n");
      out.write("               <td><input type=\"text\" name=\"userId\" id=\"userId\"\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td><label>PW:</label><td>\r\n");
      out.write("               <td><input type=\"password\" name=\"userPwd\" id=\"userPwd\" ></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         \r\n");
      out.write("         </table>\r\n");
      out.write("         <div class=\"btns\" align=\"center\">\r\n");
      out.write("            <div id=\"LoginBtn\"><input type=\"submit\" value=\"로그인\"></div>\r\n");
      out.write("            <div id=\"memberJoinBtn\" onclick=\"memberJoin();\">회원가입</div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
