/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-21 07:51:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import product.model.vo.*;
import artistapply.model.vo.*;
import java.util.ArrayList;
import member.model.vo.Member;

public final class productdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/product/../common/menubar.jsp", Long.valueOf(1590047285721L));
    _jspx_dependants.put("/views/product/../common/footer.jsp", Long.valueOf(1589256769211L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("product.model.vo");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("artistapply.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');


product plist = (product)request.getAttribute("plist");
ArrayList<Attachment> alist = (ArrayList<Attachment>)request.getAttribute("alist");
ArrayList<product> sizelist = (ArrayList<product>)request.getAttribute("sizelist");
Apply apply = (Apply)request.getAttribute("aplly");
masterpiece mp = (masterpiece)request.getAttribute("mp");
MasterpieceCount mc = (MasterpieceCount)request.getAttribute("mc");




      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- link rel=\"stylesheet\" href=\"../css/style.css\" -->\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/bootstrap.css\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/views/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write(" <!— Swiper JS —>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/views/js/swiper.min.js\"></script>\r\n");
      out.write("    <!-- Link Swiper's CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/swiper.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#sumnailimage {\r\n");
      out.write("   border: solid 1px;\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 528px;\r\n");
      out.write("   height: 507px;\r\n");
      out.write("   margin-left: 191px;\r\n");
      out.write("   margin-right: 20px;\r\n");
      out.write("   margin-top: 20px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#data {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 760px;\r\n");
      out.write("   height: 400px;\r\n");
      out.write("   float: left;\r\n");
      out.write("   margin-left: 20px;\r\n");
      out.write("   margin-right: 0px;\r\n");
      out.write("   margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#simulationMain {\r\n");
      out.write("   position : relative;<!--안에 이미지에 대한 기준-->\r\n");
      out.write("   border: solid 1px;\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 369px;\r\n");
      out.write("   height: 358px;\r\n");
      out.write("   margin-left: 191px;\r\n");
      out.write("   margin-right: 20px;\r\n");
      out.write("   margin-top: 20px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("#simulation1{\r\n");
      out.write("border: solid 1px;\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 121px;\r\n");
      out.write("   height: 125px;\r\n");
      out.write("   margin-left: 50px;\r\n");
      out.write("   margin-right: 20px;\r\n");
      out.write("   margin-top: 100px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("#simulation2{\r\n");
      out.write("border: solid 1px;\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 121px;\r\n");
      out.write("   height: 125px;\r\n");
      out.write("   margin-left: 10px;\r\n");
      out.write("   margin-right: 20px;\r\n");
      out.write("   margin-top: 100px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("#simulation3{\r\n");
      out.write("border: solid 1px;\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 121px;\r\n");
      out.write("   height: 125px;\r\n");
      out.write("   margin-left: 10px;\r\n");
      out.write("   margin-right: 20px;\r\n");
      out.write("   margin-top: 100px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#writer {\r\n");
      out.write("   border: solid 1px;\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 369px;\r\n");
      out.write("   height: 358px;\r\n");
      out.write("   margin-left: 191px;\r\n");
      out.write("   margin-right: 20px;\r\n");
      out.write("   margin-top: 20px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("#data2 {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 760px;\r\n");
      out.write("   height: 358px;\r\n");
      out.write("   float: left;\r\n");
      out.write("   margin-left: 10px;\r\n");
      out.write("   margin-right: 0px;\r\n");
      out.write("   margin-top: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ul,li{\r\n");
      out.write("      list-style:none;\r\n");
      out.write("      }\r\n");
      out.write("  #slide{\r\n");
      out.write("      height:400px;\r\n");
      out.write("      width: 700px;\r\n");
      out.write("      position:relative;\r\n");
      out.write("      overflow:hidden;\r\n");
      out.write("     \r\n");
      out.write("      }\r\n");
      out.write("  #slide ul{\r\n");
      out.write("      width:400%;\r\n");
      out.write("      height:200%;\r\n");
      out.write("      transition:1s;\r\n");
      out.write("      }\r\n");
      out.write("  #slide li{\r\n");
      out.write("      float: left;\r\n");
      out.write("      }\r\n");
      out.write("  #slide input{\r\n");
      out.write("      display:none;\r\n");
      out.write("      }\r\n");
      out.write("  #slide label{\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      vertical-align:middle;\r\n");
      out.write("      margin-left:10px;\r\n");
      out.write("      margin-right:10px;\r\n");
      out.write("      margin-bottom:0px;\r\n");
      out.write("      width:15px;\r\n");
      out.write("      height:15px;\r\n");
      out.write("      border:3px solid rgb(0, 0, 0);\r\n");
      out.write("      transition:0.3s;\r\n");
      out.write("      border-radius:50%;\r\n");
      out.write("      cursor:pointer;\r\n");
      out.write("      }\r\n");
      out.write("  #slide .pos{\r\n");
      out.write("      text-align:center;\r\n");
      out.write("      position:absolute;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      left:0;\r\n");
      out.write("      width:100%;\r\n");
      out.write("      }\r\n");
      out.write("    #pos1:checked~ul{\r\n");
      out.write("      margin-left:0%;\r\n");
      out.write("      }\r\n");
      out.write("    #pos2:checked~ul{\r\n");
      out.write("      margin-left:-702px;\r\n");
      out.write("      }\r\n");
      out.write("    #pos3:checked~ul{\r\n");
      out.write("      margin-left:-1404px;\r\n");
      out.write("      }\r\n");
      out.write("    #pos1:checked~.pos>label:nth-child(1){\r\n");
      out.write("      background:rgb(255, 255, 255);\r\n");
      out.write("      }\r\n");
      out.write("    #pos2:checked~.pos>label:nth-child(2){\r\n");
      out.write("      background:rgb(255, 255, 255);\r\n");
      out.write("      }\r\n");
      out.write("    #pos3:checked~.pos>label:nth-child(3){\r\n");
      out.write("      background:rgb(255, 255, 255);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #imgInfo { width:100%; }\r\n");
      out.write("      #imgInfo td { width:50%; font-size:20px; line-height:2; }\r\n");
      out.write("      .btnArea { width:100%; margin:10px 0; }\r\n");
      out.write("\t  .btnArea:after { display:block; content:\"\"; clear:both; }\r\n");
      out.write("\t .btn{\r\n");
      out.write("\t \twidth:550px;\r\n");
      out.write("\t \theight:40px;\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t  <!-- Demo styles -->\r\n");
      out.write("  <style>\r\n");
      out.write("    html, body {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    body {\r\n");
      out.write("      background: #eee;\r\n");
      out.write("      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color:#000;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .swiper-container {\r\n");
      out.write("      width: 75%;\r\n");
      out.write("      height: 500px;\r\n");
      out.write("    }\r\n");
      out.write("    .swiper-slide {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 18px;\r\n");
      out.write("      background: #fff;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .swiper-fiximg {\r\n");
      out.write("       \t position : absolute;\r\n");
      out.write("       \t top : 20%;\r\n");
      out.write("       \t left : 35%;\r\n");
      out.write("       \t z-index:100;\r\n");
      out.write("       \t \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /* Center slide text vertically */\r\n");
      out.write("      display: -webkit-box;\r\n");
      out.write("      display: -ms-flexbox;\r\n");
      out.write("      display: -webkit-flex;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      -webkit-box-pack: center;\r\n");
      out.write("      -ms-flex-pack: center;\r\n");
      out.write("      -webkit-justify-content: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      -webkit-box-align: center;\r\n");
      out.write("      -ms-flex-align: center;\r\n");
      out.write("      -webkit-align-items: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\t \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');

	Member loginUser = (Member) session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath() );
      out.write("/views/css/style.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 로그인 팝업 css */\r\n");
      out.write("/* #LoginBtn input, #memberJoinBtn, #logoutBtn, #myPage {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground: red;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#memberJoinBtn {\r\n");
      out.write("\tbackground: gray;a\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginBtn:hover\r\n");
      out.write("      #memberJoinBtn:hover, #logoutBtn:hover, #memberJoinBtn:hover,\r\n");
      out.write("\t#myPage:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Login_pop {\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tmargin-top: 70px;\r\n");
      out.write("\t-webkit-transition: all 0.5s;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\ttext-align:center; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logout, #myPage {\r\n");
      out.write("\tbackground: orangered;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myPage {\r\n");
      out.write("\tbackground: yellowgreen;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#LoginArea {\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\tmargin-left: 35%;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-algin: \"center\";\r\n");
      out.write("\t\r\n");
      out.write(" display:inline-block; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginArea>form, #userInfo {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#LoginArea a img {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 1em;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("\tpadding-right: 50px;\r\n");
      out.write("}\r\n");
      out.write(" */\r\n");
      out.write("h1 {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding-top: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputinfo {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul li ul li:hover{\r\n");
      out.write("\tbackground-color:red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header id=\"menu\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"logo\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/logo-02.png\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul class=\"navi\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("\t\t\t<!-- <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/product/product.jsp\">STORE</a></li> -->\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/list.po\">STORE</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">COMMUNITY</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print( request.getContextPath() );
      out.write("/list.am\">아마추어\r\n");
      out.write("\t\t\t\t\t\t\t게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">NOTICE</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/list.no\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/list.in\">1:1문의</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t");
if(loginUser != null){ 
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"#\">TEST</a> \r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/Mo.li\">마이페이지 소비자</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">마이페이지 소비자</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">My Page(?)</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Chat</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">마이페이지 관리자</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">마이페이지 판매자</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage.me?userId=");
      out.print(loginUser.getUserId() );
      out.write("\">정보수정</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\">로그아웃</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 222222222222-->\r\n");
      out.write("\t\t <!-- <input type=\"hidden\" id = \"checkLogin\">  -->\r\n");
      out.write("\t\t\t\t<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 22222222222222222-->\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<!--icon :: 색상변경 또는 없애버리고 메뉴바 만들기-->\r\n");
      out.write("\t\t<div id=\"loginWrap\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/member/signIn.jsp\" class=\"icon\" onclick=\"login_btn();\"><img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/views/img/login2.png\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--마이페이지로 넘어가는부분 잠시 수정 -->\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"icon\"><img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/search2.png\"></a>\r\n");
      out.write("\t\t</div> <!-- loginWrap 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</header>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!--  로그인 팝업창 보류 --><!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 3333333333333-->\r\n");
      out.write("<!-- \t\t\t<script>\r\n");
      out.write("\t\t\t\t$(function (){\r\n");
      out.write("\t\t\t\t\tif($(\"#checkLogin\").length>0){\r\n");
      out.write("\t\t\t\t\t\t$(\"#LoginArea\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t</script> -->\r\n");
      out.write("\t<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 3333333333333333-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<table style = \"margin : 0 auto;\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("   <div id=\"slide\">\r\n");
      out.write("  <input type=\"radio\" name=\"pos\" id=\"pos1\" checked>\r\n");
      out.write("  <input type=\"radio\" name=\"pos\" id=\"pos2\">\r\n");
      out.write("  <input type=\"radio\" name=\"pos\" id=\"pos3\">\r\n");
      out.write("\r\n");
      out.write("  <ul>\r\n");
      out.write("  ");
for(int i =0; i< alist.size();i++){
	  Attachment a = alist.get(i);
	  if(a.getFileLevel() == 0){
      out.write("\r\n");
      out.write("    <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/thumbnail_uploadFiles/");
      out.print(a.getSavefileName());
      out.write("\" width=700px; height=400px;></li>\r\n");
      out.write("    ");
}}
      out.write("\r\n");
      out.write("     ");
for(int i =0; i< alist.size();i++){
	  Attachment a = alist.get(i);
	  if(a.getFileLevel() == 1){
      out.write("\r\n");
      out.write("    <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/thumbnail_uploadFiles/");
      out.print(a.getSavefileName());
      out.write("\" width=700px; height=400px;></li>\r\n");
      out.write("        ");
}}
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write("  <p class=\"pos\">\r\n");
      out.write("    <label for=\"pos1\"></label>\r\n");
      out.write("    <label for=\"pos2\"></label>\r\n");
      out.write("    <label for=\"pos3\"></label>\r\n");
      out.write("\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("   </td>\r\n");
      out.write("  <td style=\"box-sizing:border-box; padding: 0 0 0 50px;\">\r\n");
      out.write("      <div>\r\n");
      out.write("         <h3 align=\"left\">");
      out.print(plist.getPaint_name() );
      out.write("</h3>\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr style=\"margin: 1;\" color=\"black\" width=\"554px\">\r\n");
      out.write("      <table id=\"imgInfo\">\r\n");
      out.write("      \t<tr>\r\n");
      out.write("      \t\t<td align=\"center\">작가명 : ");
      out.print( plist.getArtist_name());
      out.write("</td>\r\n");
      out.write("      \t\t<td align=\"center\">카테고리 : ");
      out.print(plist.getCategory() );
      out.write("</td>\r\n");
      out.write("      \t</tr>\r\n");
      out.write("      \t<tr>\r\n");
      out.write("      \t\t<td align=\"center\">제작년도 : ");
      out.print(plist.getCategory() );
      out.write("</td>\r\n");
      out.write("      \t\t<td align=\"center\">사이즈 :");
 for(int i =0;i < sizelist.size();i++) {
				product p = sizelist.get(i);
				if(plist.getSize_no() == p.getSize_no() ){
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      out.print(p.getWidth());
      out.write(' ');
      out.write('*');
      out.print(+p.getHeight());
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 }}
      out.write("</td>\r\n");
      out.write("      \t</tr>\r\n");
      out.write("      </table>  \t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("      <hr style=\"margin: 1;\" color=\"black\" width=\"554px\">\r\n");
      out.write("      <table id=\"imgInfo\">\r\n");
      out.write("      <tr>\r\n");
      out.write("      <td>\r\n");
      out.write("       <span style=\"text-align: center; width: 100px; font-size: 35px;\">");
      out.print(plist.getPatint_price() );
      out.write("원</span>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td>\r\n");
      out.write("  \r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\t<div style=\"float:right;\">\r\n");
      out.write("      \t\t<div class=\"likeCount\" style=\"float:left; margin-right:10px;\">\r\n");
      out.write("      \t\t\t<span class=\"countArea\">");
      out.print(mc.getCount() );
      out.write("</span>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\t");
if(mp.getUser_id() != null){ 
      out.write("\r\n");
      out.write("      \t\t<img class=\"heartcheck\" src=\"");
      out.print(request.getContextPath());
      out.write("/views/img/colorHeart.png\">\r\n");
      out.write("      \t\t");
}else{
      out.write("\r\n");
      out.write("      \t\t<img class=\"heartcheck\" src=\"");
      out.print(request.getContextPath());
      out.write("/views/img/emptyHeart.png\">\r\n");
      out.write("      \t\t");
} 
      out.write("\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("      </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <script>\r\n");
      out.write("      $(function(){\r\n");
      out.write("      $(\".heartcheck\").click(function(){\r\n");
      out.write("    \t  var paint_no = \"");
      out.print(plist.getPaint_no());
      out.write("\";\r\n");
      out.write("    \t  var heart = $(\".heartcheck\").attr('src');\r\n");
      out.write("    \t  var heartYN;\r\n");
      out.write("\r\n");
      out.write("    \t  if(heart=='");
      out.print(request.getContextPath());
      out.write("/views/img/colorHeart.png'){\r\n");
      out.write("    \t\t  $(\".heartcheck\").attr('src','");
      out.print(request.getContextPath());
      out.write("/views/img/emptyHeart.png');\r\n");
      out.write("    \t\t  heartYN = 'N';\r\n");
      out.write("    \t  }else{\r\n");
      out.write("    \t\t  $(\".heartcheck\").attr('src','");
      out.print(request.getContextPath());
      out.write("/views/img/colorHeart.png');\r\n");
      out.write("    \t\t  heartYN = 'Y';\r\n");
      out.write("    \t  }\r\n");
      out.write("    \t  $.ajax({\r\n");
      out.write("    \t\turl:\"masterpiece.po\",\r\n");
      out.write("    \t\ttype:\"post\",\r\n");
      out.write("    \t\tdata:{paint_no:paint_no,heartYN:heartYN},\r\n");
      out.write("   \r\n");
      out.write("    \t\tsuccess:function(data){\r\n");
      out.write("    \t\t\tvar $likeCount = $(\".likeCount\");\r\n");
      out.write("    \t\t\tvar $count = $(\"<span>\").text(data);\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t$likeCount.html($count);\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t},\r\n");
      out.write("    \t\terror:function(request,statur,error){\r\n");
      out.write("    \t\t\talert(\"로그인을 하셔야 합니다.\");\r\n");
      out.write("    \t\t\t $(\".heartcheck\").attr('src','");
      out.print(request.getContextPath());
      out.write("/views/img/emptyHeart.png');\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t  \r\n");
      out.write("    \t  })\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  \r\n");
      out.write("      });\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("      </script>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      <div class=\"btnArea\">\r\n");
      out.write("      <input id=\"paint_no\" type=\"hidden\" value=\"");
      out.print(plist.getPaint_no());
      out.write("\">\r\n");
      out.write("\t      <input type=\"button\" class = \"btn btn-outline-dark\" value=\"바로 구매하기\"><br clear=\"both\"><br>\r\n");
      out.write("\t       <input type=\"button\" class = \"btn btn-outline-success\"  value=\"장바구니 담기\" onclick=\"장바구니\"><br clear=\"both\"><br>\r\n");
      out.write("\t      <inputtype=\"button\" class = \"btn btn-outline-danger\"  value=\"Q & A\" onclick=\"q&a\"> Q & A<input type=\"hidden\" value=\"\" id=\"mid\">\r\n");
      out.write("\t      <!-- <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ movieDetail.movie_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"movie_id\"> -->\r\n");
      out.write("\t      <input type=\"hidden\" value=\"\" id=\"movie_id\">\r\n");
      out.write("  \r\n");
      out.write("      </div>\r\n");
      out.write("       <script>\r\n");
      out.write("                  $(function(){\r\n");
      out.write("\t\t\t\t \t\t$(\".btn-outline-dark\").click(function(){\r\n");
      out.write("\t\t\t\t \t\t\tvar paint_no = $(this).parent().children(\"#paint_no\").val();\r\n");
      out.write("\t\t\t\t \t\t\t\r\n");
      out.write("\t\t\t\t \t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/Buy.po?paint_no=\"+paint_no;\r\n");
      out.write("\t\t\t\t \t\t});\r\n");
      out.write("\t\t\t\t \t\t\r\n");
      out.write("\t\t\t\t \t});\r\n");
      out.write("\t\t\t\t \t\r\n");
      out.write("                  $(function(){\r\n");
      out.write("\t\t\t\t \t\t$(\".btn-outline-success\").click(function(){\r\n");
      out.write("\t\t\t\t \t\t\tvar paint_no = $(this).parent().children(\"#paint_no\").val();\r\n");
      out.write("\t\t\t\t \t\t\t\r\n");
      out.write("\t\t\t\t \t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/basket.po?paint_no=\"+paint_no;\r\n");
      out.write("\t\t\t\t \t\t});\r\n");
      out.write("\t\t\t\t \t\t\r\n");
      out.write("\t\t\t\t \t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("      \r\n");
      out.write("  </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\t\r\n");
      out.write("   <br clear=\"both\">\r\n");
      out.write("   <br>\r\n");
      out.write("   <hr style = \"margin : 50px auto;\" color=\"black\" width=\"1300px\">\r\n");
      out.write("   <br clear=\"both\">\r\n");
      out.write("   \r\n");
      out.write("   <h3 align=\"center\">인테리어 시뮬레이션</h3>\r\n");
      out.write("     \r\n");
      out.write("  <!-- Swiper -->\r\n");
      out.write("  <div class=\"swiper-container\"> \r\n");
      out.write("  ");
for(int i =0; i< alist.size();i++){
	  Attachment a = alist.get(i);
	  if(a.getFileLevel() == 0){
      out.write("\r\n");
      out.write("     \t<img class = \"swiper-fiximg\" src=\"");
      out.print(request.getContextPath());
      out.write("/thumbnail_uploadFiles/");
      out.print(a.getSavefileName());
      out.write("\" width=\"30%\">\r\n");
      out.write("    ");
}}
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <div class=\"swiper-wrapper\">\r\n");
      out.write("      <div class=\"swiper-slide\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/views/interior/인테리어1.jpg\" width=\"100%\"></div>\r\n");
      out.write("      <div class=\"swiper-slide\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/views/interior/인테리어2.jpg\"  width=\"100%\"></div>\r\n");
      out.write("      <div class=\"swiper-slide\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/views/interior/인테리어3.jpg\"  width=\"100%\"></div>\r\n");
      out.write("      <div class=\"swiper-slide\">Slide 4</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!— Add Pagination —>\r\n");
      out.write("    <div class=\"swiper-pagination\"></div>\r\n");
      out.write("    <!— Add Arrows —>\r\n");
      out.write("    <div class=\"swiper-button-next\"></div>\r\n");
      out.write("    <div class=\"swiper-button-prev\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!— Initialize Swiper —>\r\n");
      out.write("  <script>\r\n");
      out.write("    var swiper = new Swiper('.swiper-container', {\r\n");
      out.write("      pagination: {\r\n");
      out.write("        el: '.swiper-pagination',\r\n");
      out.write("        type: 'progressbar',\r\n");
      out.write("      },\r\n");
      out.write("      navigation: {\r\n");
      out.write("        nextEl: '.swiper-button-next',\r\n");
      out.write("        prevEl: '.swiper-button-prev',\r\n");
      out.write("      },\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("   \r\n");
      out.write("   <br clear=\"both\">\r\n");
      out.write("   <hr style = \"margin : 50px auto;\" color=\"black\" width=\"1300px\">\r\n");
      out.write("   <h3 align=\"center\">작품 소개</h3>\r\n");
      out.write("   <a style=\"text-align: left; width: 100px; margin-left:300px; font-size: 15px; text-decoration: none !important; border-bottom: dotted 0px !important; color: black !important;\">");
      out.print(plist.getPaint_int() );
      out.write("</a>\r\n");
      out.write("   <br>\r\n");
      out.write("   <hr style = \"margin : 50px auto;\" color=\"black\" width=\"1300px\">\r\n");
      out.write("   <h3 align=\"center\">작가 소개</h3>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"writer\">\r\n");
      out.write("      <img src=\"");
      out.print(request.getContextPath());
      out.write("/views/interior/");
      out.print(apply.getArtist_pro() );
      out.write("\" style=\"width: 369px; height: 358px;\">\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"data2\">\r\n");
      out.write("   <a style=\"text-align: left; width: 100px; margin-left:30px; font-size: 15px; text-decoration: none !important; border-bottom: dotted 0px !important; color: black !important;\">");
      out.print(apply.getArtist_int() );
      out.write("</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <br clear=\"both\">\r\n");
      out.write("   <hr style = \"margin : 50px auto;\" color=\"black\" width=\"1300px\">\r\n");
      out.write("   <h3 align=\"center\">Q & A</h3>\r\n");
      out.write("   <br>\r\n");
      out.write("   <table style = \"margin : 0 auto;\">\r\n");
      out.write("    <tr>\r\n");
      out.write("\t\t<td style = \"margin : 0 auto;\">Q & A 작성</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("<br>\r\n");
      out.write("\t<td><textArea rows=\"5\" cols=\"100\" id=\"replyContent\" style = \"margin : 50px auto;\"></textArea></td>\r\n");
      out.write("\t<td >\r\n");
      out.write("\t<button id=\"addReply\" type=\"button active\" class=\"btn btn-secondary\" style=\"width:100px; margin-left : 15px;\">Q&A 등록</button>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("   </table>\r\n");
      out.write("\r\n");
      out.write("   <br clear=\"both\">\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tbody {\r\n");
      out.write("\tmargin : 0;}\r\n");
      out.write("\r\n");
      out.write("\t.footer{\r\n");
      out.write("\t\r\n");
      out.write("\tpadding : 20px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tcolor : white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("  <div class=\"footer\">\r\n");
      out.write("    \"Copyright © 1998-2019 KH Information Educational Institute All Right Reserved\"\r\n");
      out.write("    </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
