/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-09 09:53:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/product/../common/menubar.jsp", Long.valueOf(1589017239381L));
    _jspx_dependants.put("/views/product/../common/footer.jsp", Long.valueOf(1589016906147L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../css/bootstrap.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("            #title{\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            #t1{\r\n");
      out.write("                padding: 30px;\r\n");
      out.write("                margin-left: 10%;\r\n");
      out.write("                background-color: rgb(228, 227, 227);\r\n");
      out.write("            }\r\n");
      out.write("            td{\r\n");
      out.write("                padding-left: 115px;\r\n");
      out.write("                padding-right: 115px;\r\n");
      out.write("                padding-top: 30px;\r\n");
      out.write("            }\r\n");
      out.write("             b{\r\n");
      out.write("                font-size: x-large;\r\n");
      out.write("            }\r\n");
      out.write("            #artist{\r\n");
      out.write("                height: 50px;\r\n");
      out.write("                border-width: 5px;\r\n");
      out.write("                border-color: lavender;\r\n");
      out.write("                border-style:outset;\r\n");
      out.write("                border-top-left-radius:10px; \r\n");
      out.write("                border-bottom-right-radius:10px;\r\n");
      out.write("                border-top-right-radius:10px;\r\n");
      out.write("                border-bottom-left-radius: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            #category{\r\n");
      out.write("                height: 50px;\r\n");
      out.write("                width: 170px;\r\n");
      out.write("                border-width: 5px;\r\n");
      out.write("                border-color: lavender;\r\n");
      out.write("                border-style:outset;\r\n");
      out.write("                border-top-left-radius:10px; \r\n");
      out.write("                border-bottom-right-radius:10px;\r\n");
      out.write("                border-top-right-radius:10px;\r\n");
      out.write("                border-bottom-left-radius: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            #tag_search{\r\n");
      out.write("                height: 50px;\r\n");
      out.write("                width: 950px;\r\n");
      out.write("                border-width: 5px;\r\n");
      out.write("                border-color: lavender;\r\n");
      out.write("                border-style:outset;\r\n");
      out.write("                border-top-left-radius:10px; \r\n");
      out.write("                border-bottom-right-radius:10px;\r\n");
      out.write("                border-top-right-radius:10px;\r\n");
      out.write("                border-bottom-left-radius: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            #price{\r\n");
      out.write("                background-color: red;\r\n");
      out.write("            }\r\n");
      out.write("            #submit{\r\n");
      out.write("                height: 50px;\r\n");
      out.write("                width: 100px;\r\n");
      out.write("                border-width: 5px;\r\n");
      out.write("                border-color: lavender;\r\n");
      out.write("                background: lavenderblush;\r\n");
      out.write("                border-style:outset;\r\n");
      out.write("                border-top-left-radius:10px; \r\n");
      out.write("                border-bottom-right-radius:10px;\r\n");
      out.write("                border-top-right-radius:10px;\r\n");
      out.write("                border-bottom-left-radius: 10px;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴바</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"views/css/style.css\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header id=\"menu\">\r\n");
      out.write("       <div id=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/logo-02.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("                 <ul class = \"navi\">\r\n");
      out.write("                    <li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/product/product.jsp\">STORE</a></li>\r\n");
      out.write("                    <li><a href=\"#\">COMMUNITY</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">아마추어 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">NOTICE</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("                        </ul>    \r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("        <!--icon :: 색상변경 또는 없애버리고 메뉴바 만들기-->\r\n");
      out.write("        <div id=\"loginWrap\">\r\n");
      out.write("            <a href =\"#\" class=\"icon\" ><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/login2.png\"></a>\r\n");
      out.write("            <a href =\"#\" class=\"icon\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/views/img/search2.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header> \r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<br clear=\"both\"><br>\r\n");
      out.write("       <h1 id=\"title\">미술품 판매(가제)</h1>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"search\">\r\n");
      out.write("            <form>\r\n");
      out.write("            <table id=\"t1\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><b>작가 명</b><br><input type=\"search\" id=\"artist\"></td>\r\n");
      out.write("                    <td><b>분류</b><br><select name=\"category\" id=\"category\">\r\n");
      out.write("                                <option value=\"figure painting\">인물화</option>\r\n");
      out.write("                                <option value=\"landscape painting\">풍경화</option>\r\n");
      out.write("                    </select></td>\r\n");
      out.write("                    <td><b id=\"p\">가격</b><br><input type=\"range\" id=\"price\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"3\"><b>태그 검색</b><br><input type=\"search\" id=\"tag_search\" placeholder=\"내용을 입력해주세요\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td><button type=\"submit\" id=\"submit\">검색</button></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("   <br><br><br><br><br><br><br><br><br>\r\n");
      out.write("   <br><br><br><br><br><br><br><br><br>\r\n");
      out.write("   <br><br><br><br><br><br><br><br><br>\r\n");
      out.write("   <br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    \"Copyright © 1998-2019 KH Information Educational Institute All Right Reserved\"\r\n");
      out.write("   </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
